PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE IF NOT EXISTS tag(
    name VARCHAR(64) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS alias(
    s VARCHAR(64) PRIMARY KEY NOT NULL,
    name VARCHAR(64) NOT NULL,
    FOREIGN KEY(name) REFERENCES tag(name)
);

CREATE TABLE IF NOT EXISTS pic(
    pid INTEGER PRIMARY KEY NOT NULL,
    uid INTEGER NOT NULL,
    series INTEGER NOT NULL,
    stat INTEGER NOT NULL,
    views INTEGER NOT NULL,
    bookmark INTEGER NOT NULL,
    count INTEGER NOT NULL,
    timestamp INTEGER NOT NULL
    title VARCHAR(64) NOT NULL,
);


CREATE TABLE IF NOT EXISTS pic_tag(
    pid INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    FOREIGN KEY(pid) REFERENCES pic(pid)
    FOREIGN KEY(name) REFERENCES tag(name)
    PRIMARY KEY(pid,name)
);
